### ISSUE TITLE
Support ASCII file

### ISSUE THREAD

**Issue by madeindjs** [manute/rawsql#1]
I want to open a MySQL dump but I had this error

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

This is my file type

```bash
$ file -i dump.sql
dump.sql: text/plain; charset=us-ascii
```

**Comment by manute** [comment]
Hey @madeindjs thanks for the issue. 

But if the file is converted to `utf8` it is working no?

**Comment by madeindjs** [comment]
In fact this error is due to [`String`](https://doc.rust-lang.org/std/string/struct.String.html)'s Rust object who must be UTF-8 encoded. Bellow the Rust definition of [`String`](https://doc.rust-lang.org/std/string/struct.String.html)

> A UTF-8 encoded, growable string.

The problem come from your `Loader` struct. The only method is

~~~rust
impl Loader {
    ///Given a path of file retrieve all the queries.
    pub fn get_queries_from(path: &str) -> Result<Loader> {
~~~

This methode use `fn read_file(path: &str) -> Result<String>` who only support UTF-8 encoded file.

I think it would be  grate to create a new method

~~~rust
impl Loader {
    ///Given a path of file retrieve all the queries.
    pub fn get_queries_from_str(dump: &str) -> Result<Loader> {
~~~

What do you think about?

**Comment by manute** [comment]
https://doc.rust-lang.org/std/string/struct.String.html#utf-8
>  if you need a non-UTF-8 string, consider OsString

I think it would need to accept a [OsString](https://doc.rust-lang.org/std/ffi/struct.OsString.html) or a `bytes` (that I think is more correct) . 

The problem is this will change a bit the library and the api, and it will be a big refactor in the code because all is tight to `&str`. 

I don't know if it's worthy for now. 🤔 

Btw , in the meantime what you can do is convert the ascii file to utf8 (I know it's not the best solution but it will work)

**Comment by madeindjs** [comment]
I thinks your right, thank you so much for your answer !
